# Generated by Django 2.0.7 on 2018-09-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pcontent',
            field=models.TextField(default='content'),
        ),
    ]
