# Generated by Django 2.0.7 on 2018-09-07 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coding', '0002_post_pcontent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
