# Generated by Django 2.0.7 on 2018-09-18 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding', '0003_delete_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='read',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(max_length=10)),
            ],
        ),
    ]
